# Generated by Django 5.1.1 on 2024-09-24 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Email', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Почта')),
                ('Account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('Description', models.CharField(max_length=500, verbose_name='Описание')),
                ('Author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.student')),
            ],
        ),
    ]
